export const styles = {
  container: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "100vh",
    width: "100vw",
    position: "relative",
    overflow: "hidden",
  },
  backgroundImage: (isActive) => ({
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    backgroundSize: "cover",
    backgroundPosition: "center",
    opacity: isActive ? 1 : 0,
    transition: "opacity 1s ease-in-out",
    zIndex: 0,
  }),
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    zIndex: 1,
  },
  form: {
    padding: "2.5rem",
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    borderRadius: "16px",
    boxShadow: "0 8px 32px rgba(0, 0, 0, 0.1)",
    width: "100%",
    maxWidth: "400px",
    backdropFilter: "blur(10px)",
    zIndex: 2,
    transform: "translateY(0)",
    transition: "transform 0.3s ease",
    position: "relative",
    overflow: "hidden",
  },
  errorContainer: {
    backgroundColor: "#fee2e2",
    color: "#dc2626",
    padding: "0.75rem",
    borderRadius: "8px",
    marginBottom: "1.5rem",
    textAlign: "center",
    fontSize: "0.9rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.5rem",
  },
  inputContainer: {
    position: "relative",
    marginBottom: "1rem",
  },
  input: {
    width: "100%",
    padding: "0.75rem",
    paddingLeft: "2.5rem",
    border: "2px solid #e2e8f0",
    borderRadius: "8px",
    fontSize: "1rem",
    transition: "all 0.3s ease",
    textAlign: "right",
  },
  inputFocus: {
    borderColor: "#3498db",
    outline: "none",
    boxShadow: "0 0 0 3px rgba(52, 152, 219, 0.1)",
  },
  icon: {
    position: "absolute",
    left: "10px",
    top: "40%",
    transform: "translateY(-50%)",
    color: "#64748b",
    fontSize: "1.2rem",
  },
  passwordToggle: {
    position: "absolute",
    left: "10px",
    top: "50%",
    transform: "translateY(-50%)",
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "5px",
    color: "#64748b",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "color 0.3s ease",
  },
  submitButton: (isLoading) => ({
    width: "100%",
    padding: "0.75rem",
    backgroundColor: isLoading ? "#93c5fd" : "#3498db",
    color: "white",
    border: "none",
    borderRadius: "8px",
    cursor: isLoading ? "not-allowed" : "pointer",
    opacity: isLoading ? 0.7 : 1,
    fontSize: "1rem",
    fontWeight: "600",
    transition: "all 0.3s ease",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.5rem",
  }),
  decorativeCircle: (position, colors) => ({
    position: "absolute",
    ...position,
    width: position.size || "100px",
    height: position.size || "100px",
    background: `linear-gradient(45deg, ${colors[0]}, ${colors[1]})`,
    borderRadius: "50%",
    opacity: 0.1,
  }),
};
