export const styles = {
  container: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "100vh",
    width: "100vw",
    position: "relative",
    overflow: "hidden",
    backgroundColor: "#f5f8fa",
  },
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    zIndex: 1,
  },
  form: {
    padding: "2rem",
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    borderRadius: "8px",
    boxShadow: "0 8px 32px rgba(0, 0, 0, 0.1)",
    width: "100%",
    border: "1px solid #e2e8f0",
    maxWidth: "550px",
    backdropFilter: "blur(10px)",
    zIndex: 2,
    transform: "translateY(0)",
    transition: "transform 0.3s ease",
    position: "relative",
    overflow: "hidden",
  },
  errorContainer: {
    backgroundColor: "#fee2e2",
    color: "#dc2626",
    padding: "0.75rem",
    borderRadius: "8px",
    marginBottom: "1.5rem",
    textAlign: "center",
    fontSize: "0.9rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.5rem",
  },
  inputContainer: {
    position: "relative",
    marginBottom: "1rem",
  },

  submitButton: (isLoading) => ({
    width: "100%",
    padding: "0.75rem",
    backgroundColor: isLoading ? "#93c5fd" : "#3498db",
    color: "white",
    border: "none",
    borderRadius: "8px",
    cursor: isLoading ? "not-allowed" : "pointer",
    opacity: isLoading ? 0.7 : 1,
    fontSize: "1rem",
    fontWeight: "600",
    transition: "all 0.3s ease",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.5rem",
  }),
  decorativeCircle: (position, colors) => ({
    position: "absolute",
    ...position,
    width: position.size || "100px",
    height: position.size || "100px",
    background: `linear-gradient(45deg, ${colors[0]}, ${colors[1]})`,
    borderRadius: "50%",
    opacity: 0.1,
  }),
};
